### ISSUE TITLE
Do you have this dataset?

### ISSUE THREAD

**Issue by kopyl** [Wenxin-Jiang/CS577-NLP#1]
Hey. Is there any chance you have this dataset cached locally and can send it to me?

https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_6plus

I'm going to train miniSDXL (like lambdalabs/miniSD-diffusers, but for SDXL) and need the exact same dataset which was used here... 

Just close and delete this issue please if you can't help me.

**Comment by Wenxin-Jiang** [comment]
Hi,

I don't have the dataset, but I am aware of a dataset named [HFCommunity](https://som-research.github.io/HFCommunity/) that might include it. Hope this is helpful!

**Comment by kopyl** [comment]
@Wenxin-Jiang thank you very much :)
